# https://github.com/actions/starter-workflows/blob/c934669ce246e6d64e54006b714b04199cbe445b/ci/node.js.yml

name: Node.js CI

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # https://github.com/arjun27/playwright-github-actions
    container: arjun27/playwright-bionic:0.2.0

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm run build
      - run: npm run npm:install:examples
      - run: npm run build:examples
      - run: npm run lint
      - run: npm run test:coverage
      - run: npm run test:examples
        env:
          CI: true
